### ISSUE TITLE
Connect INT line

### ISSUE THREAD

**Issue by chaseblock** [lhr-solar/BPS-AmperesPCB-Daybreak#1]
A nice-to-have on a future revision of this board would include a connection of the INT line to the BPS leader board. This would allow us to configure a threshold for the Ampere board to watch for, so that the leader board would be notified if that threshold were crossed. This would save compute resources on the leader.

The BPS leader board would also have to be adjusted to allow for this, or else use an unconnected GPIO.

**Comment by ClarkPoon** [comment]
This is irrelevant with the new ADC. This only applies to the old version with the AS8510
