### ISSUE TITLE
J2 Connections Need to be Flipped

### ISSUE THREAD

**Issue by HannahSLee14** [lhr-solar/BPS-AmperesPCB-Daybreak#4]
BPS Leader board has the connections for J2 flipped. We need to change the order of the traces/connections on this connector so it aligns with the Leader board.

**Comment by ClarkPoon** [comment]
Fixed by @chaseblock 's commit: https://github.com/lhr-solar/BPS-AmperesPCB/commit/098b2f3f24c678263e1551fa4867fb32e6bfda07
